### ISSUE TITLE
Windows install requires PowerShell run as Admin (script's elevation doesn't seem to work)

### ISSUE THREAD

**Issue by pperrin** [small-tech/site.js#10]
Running install from non-admin shows no error, but doesn't install site.js.

Once installed (having launched powershell as admin) it seems to install fine.

Launching site the first time from non-admin powershell asks for permissions to install a certificate, but the install fails due to no rights in install it.

Error: Command failed: C:\Users\xxxxx\.small-tech.org\site.js\tls\local\mkcert-v1.4.1-windows-amd64 -install
Created a new local CA at "C:\Users\xxxxxx\.small-tech.org\site.js\tls\local" �
The local CA is now installed in the system trust store! ⚡️
Note: Firefox support is not available on your platform. ℹ️
ERROR: failed to execute "keytool -importcert": exit status 1

Certificate was added to keystore
keytool error: java.io.FileNotFoundException: C:\Program Files\Java\jdk1.8.0_131\jre\lib\security\cacerts (Access is denied)

    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Function.createServer (C:\Program Files\site.js\node_modules\@small-tech\auto-encrypt-localhost\index.js:98:22)
    at Object.smallTechHttps.createServer (C:\Program Files\site.js\node_modules\@small-tech\https\index.js:42:56)
    at Site._createServer (C:\Program Files\site.js\index.js:787:18)
    at Site.createServer (C:\Program Files\site.js\index.js:626:24)
    at new Site (C:\Program Files\site.js\index.js:277:10)
    at C:\Program Files\site.js\bin\commands\serve.js:212:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 43 72 65 61 74 65 64 20 61 20 6e 65 77 20 6c 6f 63 61 6c 20 43 41 20 61 74 20 22 43 3a 5c 55 73 65 72 73 5c 70 61 75 6c 5c 2e 73 6d 61 6c 6c 2d 74 65 ... 384 more bytes>
  ],
  pid: 46364,
  stdout: <Buffer >,
  stderr: <Buffer 43 72 65 61 74 65 64 20 61 20 6e 65 77 20 6c 6f 63 61 6c 20 43 41 20 61 74 20 22 43 3a 5c 55 73 65 72 73 5c 70 61 75 6c 5c 2e 73 6d 61 6c 6c 2d 74 65 ... 384 more bytes>
}

**Comment by aral** [comment]
Hey @pperrin,

Thank you for the report and sorry for the hassle.

I just tried and I can’t reproduce this on my Windows machine while running the installation under Windows Terminal without admin privileges.

I’ll keep trying.

**Comment by pperrin** [comment]
Hi

I went back to see if I could get more info to debug this - and see that the install is supported on powershell running under windows terminal. I was running locally, not under terminal -- this may have been the problem.

If so, sorry to have wasted your time!

**Comment by aral** [comment]
Thanks for the update, Paul, and no worries.

Yes, Site.js is only supported via Windows Terminal on Windows 10. It seems every terminal app behaves differently so that’s the only way I can manage to support that platform as the only dev :)

Not a waste of time at all; appreciate your feedback. If you were confused, clearly others will be also. I’ll look to see how that requirement can be made even clearer in the instructions.

**Comment by jonoabroad** [comment]
Hey, 

I appear to be getting a similar error, I believe I am running things correctly. 

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
                                                                                                                                                                       Try the new cross-platform PowerShell https://aka.ms/pscore6                                                                                                                                                                                                                                                                                  PS C:\Users\jono> iex(iwr -UseBasicParsing https://sitejs.org/install.txt).Content                                                                                      📡 Downloading Site.js 20210103130813 (16.0.5/d4fe1e9)…

 📦 Installing…
 🎉 Done!

PS C:\Users\jono> cd ..\..\dev\
PS C:\dev> mkdir jonoabroad.com


    Directory: C:\dev


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         8/02/2021     14:57                jonoabroad.com


PS C:\dev>  cd .\jonoabroad.com\
PS C:\dev\jonoabroad.com> echo 'Hello, world' | Out-File -Encoding UTF8 index.html
PS C:\dev\jonoabroad.com> site

[Windows hostname warning] Your primary DNS suffix is not set so we cannot calculate your hostname (full computer name). We are falling back to your computer name as retuned by os.hostname(). The app you’re running will most likely not work properly. To set your primary DNS suffix on Windows 10, go to Control Panel → System And Security → System → Change Settings link (next to Computer name) → [Change…] Button → [More…] Button → enter your domain name under Primary DNS suffix of this computer.


   �    ███████ ██ ████████ ███████         ██ ███████
         ██      ██    ██    ██              ██ ██     
         ███████ ██    ██    █████           ██ ███████
              ██ ██    ██    ██         ██   ██      ██
         ███████ ██    ██    ███████ ██  █████  ███████

         Created January 3rd, 2021 at 13:08:13

         Version 20210103130813-16.0.5-d4fe1e9-windows/x64
         Node.js 12.16.2
         Hugo    0.78.0

         Base    https://sitejs.org/nexe/win32-x64-12.16.2
         Source  https://source.small-tech.org/site.js/app/-/tree/d4fe1e9

         ╔═══════════════════════════════════════════╗
         ║ Like this? Fund us!                       ║
         ║                                           ║
         ║ We’re a tiny, independent not-for-profit. ║
         ║ https://small-tech.org/fund-us            ║
         ╚═══════════════════════════════════════════╝

   �    ❨site.js❩ Using locally-trusted certificates.
   �    ❨https❩ Creating server at localhost with locally-trusted certificates.
   �    ❨auto-encrypt-localhost❩ Setting up…
   �    ❨auto-encrypt-localhost❩ Creating local certificate authority (local CA) using mkcert…

 Error: Command failed: C:\Users\jono\.small-tech.org\site.js\tls\local\mkcert-v1.4.2-windows-amd64 -install
Created a new local CA �
The local CA is now installed in the system trust store! ⚡️
Note: Firefox support is not available on your platform. ℹ️
ERROR: failed to execute "keytool -importcert": exit status 1

Certificate was added to keystore
keytool error: java.io.FileNotFoundException: C:\Program Files\Java\jdk1.8.0_211\jre\lib\security\cacerts (Access is denied)


    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Function.createServer (C:\Program Files\site.js\node_modules\@small-tech\auto-encrypt-localhost\index.js:98:22)
    at Object.smallTechHttps.createServer (C:\Program Files\site.js\node_modules\@small-tech\https\index.js:42:56)
    at Site._createServer (C:\Program Files\site.js\index.js:889:18)
    at Site.createServer (C:\Program Files\site.js\index.js:722:24)
    at new Site (C:\Program Files\site.js\index.js:337:10)
    at C:\Program Files\site.js\bin\commands\serve.js:232:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 43 72 65 61 74 65 64 20 61 20 6e 65 77 20 6c 6f 63 61 6c 20 43 41 20 f0 9f 92 a5 0a 54 68 65 20 6c 6f 63 61 6c 20 43 41 20 69 73 20 6e 6f 77 20 69 6e ... 331 more bytes>
  ],
  pid: 7968,
  stdout: <Buffer >,
  stderr: <Buffer 43 72 65 61 74 65 64 20 61 20 6e 65 77 20 6c 6f 63 61 6c 20 43 41 20 f0 9f 92 a5 0a 54 68 65 20 6c 6f 63 61 6c 20 43 41 20 69 73 20 6e 6f 77 20 69 6e ... 331 more bytes>
}
PS C:\dev\jonoabroad.com>
```


Following the instructions on the github readme 

```
PS C:\dev\jonoabroad.com>  site . "@hostname"

[Windows hostname warning] Your primary DNS suffix is not set so we cannot calculate your hostname (full computer name). We are falling back to your computer name as retuned by os.hostname(). The app you’re running will most likely not work properly. To set your primary DNS suffix on Windows 10, go to Control Panel → System And Security → System → Change Settings link (next to Computer name) → [Change…] Button → [More…] Button → enter your domain name under Primary DNS suffix of this computer.


   �    ███████ ██ ████████ ███████         ██ ███████
         ██      ██    ██    ██              ██ ██     
         ███████ ██    ██    █████           ██ ███████
              ██ ██    ██    ██         ██   ██      ██
         ███████ ██    ██    ███████ ██  █████  ███████

         Created January 3rd, 2021 at 13:08:13

         Version 20210103130813-16.0.5-d4fe1e9-windows/x64
         Node.js 12.16.2
         Hugo    0.78.0

         Base    https://sitejs.org/nexe/win32-x64-12.16.2
         Source  https://source.small-tech.org/site.js/app/-/tree/d4fe1e9

         ╔═══════════════════════════════════════════╗
         ║ Like this? Fund us!                       ║
         ║                                           ║
         ║ We’re a tiny, independent not-for-profit. ║
         ║ https://small-tech.org/fund-us            ║
         ╚═══════════════════════════════════════════╝

   �    ❨site.js❩ Using globally-trusted certificates.
   �    ❨site.js❩ No aliases. Only responding for DESKTOP-UFENE8T.
   �    ❨https❩ Creating server with globally-trusted Let’s Encrypt certificates.
   ⚙️    ❨auto-encrypt❩ Configuration initialised.
   �    ❨auto-encrypt❩ Certificate does not exist; will be provisioned on first hit of the server.
   �    ❨https❩ Created HTTPS server.
   �‍♀️  ❨site.js❩ Ensuring domains are reachable before starting global server.
   ✨    ❨site.js❩ Pre-flight domain reachability check server started.
   ✨    ❨site.js❩ Attempting to reach domain DESKTOP-UFENE8T…
   �    ❨site.js❩ DESKTOP-UFENE8T is reachable.
   ✨    ❨site.js❩ Pre-flight domain reachability check server stopped.
   �    ❨site.js❩ Watching for changes to dynamic and wildcard routes.
   �    ❨auto-encrypt❩ HTTP server is listening on port 80.
   �    ❨site.js❩ Serving current directory on https://DESKTOP-UFENE8T

   �    ❨site.js❩ For statistics, see https://DESKTOP-UFENE8T/12861eb240136e21435382f59bf1c1a1

   �    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain desktop-ufene8t (valid domain is DESKTOP-UFENE8T).
   �    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain desktop-ufene8t (valid domain is DESKTOP-UFENE8T).
   �    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
   �    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain desktop-ufene8t (valid domain is DESKTOP-UFENE8T).
   �    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain desktop-ufene8t (valid domain is DESKTOP-UFENE8T).
   �    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain desktop-ufene8t (valid domain is DESKTOP-UFENE8T).
   �    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain desktop-ufene8t (valid domain is DESKTOP-UFENE8T).
   �    ❨auto-encrypt❩ Redirecting HTTP request to HTTPS.
   �    ❨auto-encrypt❩ SNI: Not responding to request for unsupported domain desktop-ufene8t (valid domain is DESKTOP-UFENE8T).
```
