### ISSUE TITLE
EADDRINUSE address already in use

### ISSUE THREAD

**Issue by angelogladding** [small-tech/site.js#18]
Trying to run `site serve . @localhost:6666` fails with:

    webhost@example:~/site_js$ site serve . @localhost:6666

    🌱    Site.js

    Created October 29th, 2020 at 12:00:36

         Version 20201029120036-15.3.1-0799d4a-linux/x64
         Node.js 12.16.2
         Hugo    0.64.1

         Base    https://sitejs.org/nexe/linux-x64-12.16.2
         Source  https://source.small-tech.org/site.js/app/-/tree/0799d4a

         ╔═══════════════════════════════════════════╗
         ║ Like this? Fund us!                       ║
         ║                                           ║
         ║ We’re a tiny, independent not-for-profit. ║
         ║ https://small-tech.org/fund-us            ║
         ╚═══════════════════════════════════════════╝

    😇    ❨site.js❩ Linux: about to disable privileged ports so we can bind to ports < 1024.
         ❨site.js❩ For details, see: https://source.small-tech.org/site.js/app/-/issues/169
    🚧    ❨site.js❩ Using locally-trusted certificates.
    🔒    ❨https❩ Creating server at localhost with locally-trusted certificates.
    📜    ❨auto-encrypt-localhost❩ Local development TLS certificate exists.
    🔒    ❨https❩ Created HTTPS server.
    🐁    ❨site.js❩ Watching for changes to dynamic and wildcard routes.
    events.js:287
      throw er; // Unhandled 'error' event
      ^

    Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at /usr/local/bin/node_modules/@small-tech/auto-encrypt-localhost/lib/HttpServer.js:132:21
    at new Promise (<anonymous>)
    at HttpServer.init (/usr/local/bin/node_modules/@small-tech/auto-encrypt-localhost/lib/HttpServer.js:130:11)
    at Function.getSharedInstance (/usr/local/bin/node_modules/@small-tech/auto-encrypt-localhost/lib/HttpServer.js:36:33)
    at Server.server.listen (/usr/local/bin/node_modules/@small-tech/auto-encrypt-localhost/index.js:153:18)
    at Site.serve (/usr/local/bin/index.js:973:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

    {
    code: 'EADDRINUSE',
    errno: 'EADDRINUSE',
    syscall: 'listen',
    address: '::',
    port: 80
    }

That was tough to copy/paste.. It installed successfully and I ran both commands with the same non-root user. No matter what port I provide it seems to be trying 80. I tried prefixing with sudo, same result. I'm using vanilla Debian 10.

**Comment by angelogladding** [comment]
I saw the issue you closed yesterday and tried it with a free :80 and it works..
