### ISSUE TITLE
site enable --owncast gives error

### ISSUE THREAD

**Issue by mroberts1** [small-tech/site.js#46]
I set up an Owncast instance and it appears to be configured correctly. I then installed Owncast per the instructions on the site, but when I run site enable --owncast the server doesn't launch and I get this error:

 ✨    ❨site.js❩ Launching server…
(node:5811) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'index' of null
    at /usr/local/bin/bin/commands/enable.js:315:63
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:5811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5811) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aral** [comment]
Ah, darn, looks like it’s failing on an assumption with an error message so we don’t know what the actual error is.

What OS is your instance running?

Worst case scenario, would you be up for giving me access to the server so I can ssh in and poke around?

**Comment by mroberts1** [comment]
Sorry, I have no experience configuring servers so am just trying to follow documentation. My Linode IP is 45.79.155.25 but I have no idea how to permission you in via ssh.

Regarding the Owncast issue, it seems that it was already running on port 8080 and I was able to connect to the admin page so that seems to be working.

But for testing the site.js install, when I do <site enable> I get the error in my initial message. 

<site> appears to launch the server okay, but I'm not sure where to access it - it says localhost but opening http://45.79.155.25/ (my Linode IP) just opens the Caddy welcome message. (So it seems that I also have to buy and set up a domain  first?) Sorry but I haven't done any of this before and am finding setting up a server very confusing.
